// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfb7Isi_GmQoYJmMz87rSD3cQ2UY0NJX8',
    appId: '1:21944934644:web:d18c524bdcfd355b5cfea1',
    messagingSenderId: '21944934644',
    projectId: 'medisep-a36c1',
    authDomain: 'medisep-a36c1.firebaseapp.com',
    storageBucket: 'medisep-a36c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEoQSlcvK-uugv-GhiO_p5BS3WKrOB13I',
    appId: '1:21944934644:android:5c46fcf3ff94349f5cfea1',
    messagingSenderId: '21944934644',
    projectId: 'medisep-a36c1',
    storageBucket: 'medisep-a36c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASP8tdL-t4RbS6abpJM3hiZ_tSpHEap7M',
    appId: '1:21944934644:ios:217a6634278cedca5cfea1',
    messagingSenderId: '21944934644',
    projectId: 'medisep-a36c1',
    storageBucket: 'medisep-a36c1.firebasestorage.app',
    iosBundleId: 'com.example.medicep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASP8tdL-t4RbS6abpJM3hiZ_tSpHEap7M',
    appId: '1:21944934644:ios:217a6634278cedca5cfea1',
    messagingSenderId: '21944934644',
    projectId: 'medisep-a36c1',
    storageBucket: 'medisep-a36c1.firebasestorage.app',
    iosBundleId: 'com.example.medicep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfb7Isi_GmQoYJmMz87rSD3cQ2UY0NJX8',
    appId: '1:21944934644:web:997a290bbe7327575cfea1',
    messagingSenderId: '21944934644',
    projectId: 'medisep-a36c1',
    authDomain: 'medisep-a36c1.firebaseapp.com',
    storageBucket: 'medisep-a36c1.firebasestorage.app',
  );
}
